name: Windows RDP

on:
  workflow_dispatch:
jobs:
  rdp:
    runs-on: windows-latest
    steps:
       - name: Download repository files
         uses: actions/checkout@v2

       - name: Enable RDP
         run: powershell.exe -File enable-access.ps1
       
       - name: Adding User..
         run: powershell.exe -File add-user.ps1
         
       - name: Adding Token And Opening TCP
         run: powershell.exe -File tcp_token.ps1
