name: rdp-2019

on:

  workflow_dispatch:

jobs:

  rdp:

    runs-on: windows-2019

    steps:

       - name: Download repository files

         uses: actions/checkout@v2

       - name: Enable RDP

         run: powershell.exe -File enable-access.ps1

       

       - name: Adding Token And Opening TCP

         run: powershell.exe -File tcp-open.ps1
